#!/usr/bin/env bash

# Check if 4 parameters are passed, display usage if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign command line arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Transfer file using scp command
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"
