#!/usr/bin/env bash

# Update apt-get
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start

# Create a simple HTML page
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx
sudo /etc/init.d/nginx reload
