#!/usr/bin/env bash

# Install nginx if not installed
if ! command -v nginx >/dev/null 2>&1; then
  sudo apt-get update
  sudo apt-get install -y nginx
fi

# Configure nginx to redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

